### ISSUE TITLE
latemk的魔法注释会把当前目录的其它文件按顺序也编译了

### ISSUE THREAD

**Issue by CamuseCao** [OsbertWang/install_latex#2]
% !TeX TXS-program:compile = txs:///latexmk/{}[-xelatex -synctex=1 -interaction=nonstopmode] ，latemk的魔法注释会把当前目录的其它文件按顺序也编译了，如果这个目录放了别的文件，会浪费时间，建议在最后面的参数上加 `%.tex`，这样就只会编译当前的文件。

**Comment by OsbertWang** [comment]
非常感谢您的意见。时间这么久才注意到有人提供了 issue，这是我的粗心。再次表示敬意。
